# on:
#    workflow_dispatch:
#      inputs:
#        pull_request:
#          description: 'Pull request number'
#          required: true

# ${{ github.event.inputs.pull_request }}"

name: Deploy PR (WIP)
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const {execSync} = require('child_process');
            function echoExecSync(cmd) { console.log(cmd); execSync(cmd) }
            const r = await github.pulls.get({
              owner: 'nwtgck',
              repo: 'use-actions-netlify',
              pull_number: 3
            });
            echoExecSync(`git config user.email "github-actions[bot]@users.noreply.github.com"`);
            echoExecSync(`git config user.name "github-actions[bot]"`);
            echoExecSync(`git status`);
            console.log(r);
            const prUserName = r.data.head.user.login;
            const baseRef = r.data.base.ref;
            const headRef = r.data.head.ref;
            const fullRepoName = r.data.head.repo.full_name;
            echoExecSync(`git checkout ${baseRef}`);
            echoExecSync(`git checkout -b preview ${baseRef}`);
            echoExecSync(`git pull --no-ff https://github.com/${fullRepoName}.git ${headRef}`);
            echoExecSync(`git status`);
            echoExecSync(`git log`);
        timeout-minutes: 1
      # - name: Deploy to Netlify
      #   uses: nwtgck/actions-netlify@v1.2
      #   with:
      #     publish-dir: './public'
      #     production-branch: master
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     deploy-message: "Deploy from GitHub Actions"
      #     enable-pull-request-comment: false
      #     enable-commit-comment: false
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #   timeout-minutes: 1
